# codeDeploy 동작
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/cicdproject
permissions:
  - object: /home/ubuntu/cicdproject
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu